### ISSUE TITLE
twitter  oauth 508 错误

### ISSUE THREAD

**Issue by xdliuyong** [bigzhu/follow_center#22]

**Comment by xdliuyong** [comment]
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/tornado-4.3.dev1-py2.7-linux-x86_64.egg/tornado/web.py", line 1414, in _execute
    result = yield result
  File "/usr/lib64/python2.7/site-packages/tornado-4.3.dev1-py2.7-linux-x86_64.egg/tornado/gen.py", line 885, in run
    value = future.result()
  File "/usr/lib64/python2.7/site-packages/tornado-4.3.dev1-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 223, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado-4.3.dev1-py2.7-linux-x86_64.egg/tornado/gen.py", line 894, in run
    yielded = self.gen.send(value)
  File "/home/bigzhu/lib/ui_module/login_m.py", line 245, in get
    user_info = self.user_oper.twitterLogin(user_info, self.merge)
  File "/home/bigzhu/lib/db_bz.py", line 19, in wrapper
    return method(self, *args, **kwargs)
  File "/home/bigzhu/lib/user_bz.py", line 183, in twitterLogin
    locale=user_info['profile_location']
KeyError: 'profile_location'

**Comment by bigzhu** [comment]
修正了，还是公用库的bug ff8469a
