### ISSUE TITLE
未登录用户，一直点更多，会报错

### ISSUE THREAD

**Issue by bigzhu** [bigzhu/follow_center#7]
```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/tornado-4.3.dev1-py2.7-linux-x86_64.egg/tornado/web.py", line 1412, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "follow_center.py", line 129, in get
    messages, more, anchor = oper.getMessages(limit, self.current_user)
  File "/home/bigzhu/follow_center/oper.py", line 27, in getMessages
    messages = list(public_db.getMessages(current_user, limit=limit, god_name=god_name, offset=offset))
  File "/home/bigzhu/follow_center/public_db.py", line 206, in getMessages
    return pg.query(sql)
  File "/home/bigzhu/follow_center/pg.py", line 37, in wrapper
    return method(self, *args, **kwargs)
  File "/home/bigzhu/follow_center/pg.py", line 58, in query
    return db.query(*args, **kwargs)
  File "/home/bigzhu/lib/webpy_db.py", line 663, in query
    self._db_execute(db_cursor, sql_query)
  File "/home/bigzhu/lib/webpy_db.py", line 595, in _db_execute
    out = cur.execute(query, params)
QueryCanceledError: canceling statement due to statement timeout
```

**Comment by bigzhu** [comment]
考虑改成web app，先不管了
